### ISSUE TITLE
paper connected

### ISSUE THREAD

**Issue by HKDZ11** [nsalhab/TelecomFraudDetection#1]
Is there any paper on this project? or  May I have your permission to refer to your project to complete my coursework？

**Comment by nsalhab** [comment]
@HKDZ11 :
Yes, there is indeed a paper on this project.
It is accessible in [IEEEXPLORE](https://ieeexplore.ieee.org/document/10629612).

Authors' copy is accessible at [here](https://drive.google.com/file/d/1v_kxW-eCWrhVKRrbeUl7Si745Xga_CQh/view?usp=drive_link).

**It would be our pleasure to refer to it and cite it:** 👍 
Here is the BIBTEX code to do so:
```
@INPROCEEDINGS{10629612,
  author={Yehya, Batoul Abo and Salhab, Nazih},
  booktitle={2023 4th International Conference on Data Analytics for Business and Industry (ICDABI)}, 
  title={Telecommunications Fraud Machine Learning-based Detection}, 
  year={2023},
  volume={},
  number={},
  pages={656-661},
  keywords={Surveys;Measurement;Industries;Deep learning;Accuracy;Reviews;Prevention and mitigation;Fraud Detection;Telecommunications Fraud;Machine learning;International Revenue Share Fraud (IRSF);Wangiri;Calling Line Identification (CLI) Spoofing},
  doi={10.1109/ICDABI60145.2023.10629612}}


```
